apiVersion: v1
kind: Pod
metadata:
  name: mynginx
  labels:
    name: my-first-pod
spec:
  containers:
  - name: mynginx
    image: nginx:1.21.3
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
