apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: redis
  ports:
  - port: 6379
    targetPort: 6379
